name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - devsecops-reports
  pull_request:
    branches:
      - main

jobs:
 

  # -----------------------
  # Step 1: Build Docker Images
  # -----------------------
  docker-build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Images
        run: |
          docker build -t myorg/order-service ./order-service
          docker build -t myorg/payment-service ./payment-service

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Images
        run: |
          docker tag myorg/order-service myorg/order-service:latest
          docker tag myorg/payment-service myorg/payment-service:latest
          docker push myorg/order-service:latest
          docker push myorg/payment-service:latest

  # -----------------------
  # Step 2: Deploy to Kubernetes
  # -----------------------
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: '1.30.0'

      - name: Set Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > kubeconfig && export KUBECONFIG=kubeconfig

      - name: Deploy Services
        run: |
          kubectl apply -f k8s/order-service.yaml
          kubectl apply -f k8s/payment-service.yaml
